### ISSUE TITLE
Installation failure due to download error

### ISSUE THREAD

**Issue by maboroshin** [malisipi/NewFlow#9]
I pressed “Install NewFlow”. It remains stopped at “Extracting Electron Launcher”. It happens no matter how many times I do it. I using Windows 10.

There may have been an initial download error, since my WiFi connection was lost. Since then, the “Downloading NewFlow” process is instantaneous. The download file may be corrupted. Where is it stored?

**Comment by malisipi** [comment]
Downloaded files is located on `%temp%` (Most of situations is `C:\\Users\\your-user-name\\AppData\\Local\\Temp`).

I got a few bug reports about the installer stuck of installing. You may remove the zip file that starts `electron` in temp and retry. However i will create a new installer due to bugs of this installer. I will notify after creating new installer.

**Comment by malisipi** [comment]
I can reproduce the issue, I will fix it asap.
![resim](https://github.com/user-attachments/assets/f397f11c-52d0-45df-899c-a5cd75d0307d)

**Comment by malisipi** [comment]
Can you try this latest version. https://github.com/malisipi/NewFlow/releases/tag/windows.0.0.3

**Comment by maboroshin** [comment]
Thanks. The app was launched successfully.

**Comment by malisipi** [comment]
I'm glad to hear the update worked for you :heart: .

**Comment by maboroshin** [comment]
I have added NewFlow to AlternativeTo.
https://alternativeto.net/software/newflow/about/

Windows and Linux have fewer YouTube Client apps than other operating systems. This is especially true for Windows. It is functioning as a viewer at this time. I'm sure that as more features are added, the number of users will increase.

**Comment by malisipi** [comment]
Thank you for your support. :heart:
